
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.util.Arrays;

/*
 * LogIn.java
 *
 * Created on Feb 6, 2009, 6:14:18 PM
 */
/** author: INDRANIL BANERJEE **/
public class LogIn extends javax.swing.JFrame {

    /** Creates new form LogIn */
    public LogIn() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userMessage = new javax.swing.JOptionPane();
        changePass = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        oldPass = new javax.swing.JPasswordField();
        newPass = new javax.swing.JPasswordField();
        okPass = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwd = new javax.swing.JPasswordField();
        exit = new javax.swing.JButton();
        d_logIn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        ext = new javax.swing.JButton();
        p_logIn = new javax.swing.JButton();
        changePasButton = new javax.swing.JButton();

        userMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                messageKeyPressed(evt);
            }
        });

        changePass.setTitle("Change Password:");

        jPanel1.setBackground(new java.awt.Color(192, 219, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.textHighlight, 3, true));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 14));
        jLabel5.setForeground(java.awt.SystemColor.textHighlight);
        jLabel5.setText("Old Password:");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14));
        jLabel6.setForeground(java.awt.SystemColor.textHighlight);
        jLabel6.setText("New Password:");

        okPass.setText("OK");
        okPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPassActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(okPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel)
                .addGap(105, 105, 105))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newPass)
                    .addComponent(oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(okPass))
                .addContainerGap())
        );

        javax.swing.GroupLayout changePassLayout = new javax.swing.GroupLayout(changePass.getContentPane());
        changePass.getContentPane().setLayout(changePassLayout);
        changePassLayout.setHorizontalGroup(
            changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        changePassLayout.setVerticalGroup(
            changePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log-in");

        jPanel2.setBackground(new java.awt.Color(192, 219, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.textHighlight, 3, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chp_lock_binary.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14));
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setText("Enter password to log-in as Dealer:");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 14));
        jLabel3.setForeground(java.awt.SystemColor.textHighlight);
        jLabel3.setText("Password:");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        d_logIn.setText("Log-in");
        d_logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_logInActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14));
        jLabel4.setForeground(java.awt.SystemColor.textHighlight);
        jLabel4.setText("Log-in as Participant:");

        ext.setText("Exit");
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });

        p_logIn.setText("Log-in");
        p_logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_logInActionPerformed(evt);
            }
        });

        changePasButton.setText("Change Password");
        changePasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changePasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(p_logIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ext))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(d_logIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exit)
                                .addGap(1, 1, 1)))
                        .addComponent(jLabel1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(changePasButton)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(346, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(d_logIn)
                            .addComponent(exit))
                        .addGap(16, 16, 16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p_logIn)
                            .addComponent(ext))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void d_logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_logInActionPerformed
        /*Password authentication of Dealer*/

        // Fetch the entered password.
        password = passwd.getPassword();

        // Fetch the actual password.
        String Password = "";
        try {
            // Open the file
            FileInputStream fstream = new FileInputStream("Password.txt");

            // Convert our input stream to a
            // DataInputStream
            DataInputStream in = new DataInputStream(fstream);

            // Continue to read lines while
            // there are still some left to read
            while (in.available() != 0) {
                // Print file line to screen
                Password = in.readLine();
            }
            in.close();
        } catch (Exception e) {
            System.err.println("File Input Error " + e);
        }

        // Formatting the acual password into a char[] array
        dealerPass = new char[Password.length()];
        for (int i = 0; i < dealerPass.length; ++i) {
            dealerPass[i] = Password.charAt(i);
        }
        decrypt(dealerPass);

        // Compare password.
        if (Arrays.equals(dealerPass, passwd.getPassword())) {
            new ShareGenerate().setVisible(true);                           // Allow access if Password is authentic
            this.dispose();
        } 
        else {
            userMessage.showMessageDialog(this, "Incorrect Password !!");   // Deny access if Password is not authentic
            passwd.setText("");
        }

    }//GEN-LAST:event_d_logInActionPerformed

    private void p_logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_logInActionPerformed

        /*Participant Log-in*/
        new SecretRecovery().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_p_logInActionPerformed

    private void messageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageKeyPressed
    }//GEN-LAST:event_messageKeyPressed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        this.dispose();
    }//GEN-LAST:event_extActionPerformed

    private void changePasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasButtonActionPerformed
        /*Show password change dialog-box*/
        changePass.setSize(410, 215);
        changePass.setVisible(true);
}//GEN-LAST:event_changePasButtonActionPerformed

    private void okPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPassActionPerformed
        /*Password authentication for setting new password*/
        
        // Fetch old password
        String Password = "";
        try {
            // Open the file
            FileInputStream fstream = new FileInputStream("Password.txt");

            // Convert our input stream to a
            // DataInputStream
            DataInputStream in = new DataInputStream(fstream);

            // Continue to read lines while
            // there are still some left to read
            while (in.available() != 0) {
                // Print file line to screen
                Password = in.readLine();
            }
            in.close();
        } catch (Exception e) {
            System.err.println("File Input Error " + e);
        }

        // Formatting the actual password into char[] array
        dealerPass = new char[Password.length()];
        for (int i = 0; i < dealerPass.length; ++i) {
            dealerPass[i] = Password.charAt(i);
        }
        decrypt(dealerPass);

        // Compare passwords. If password matches, write new password in file
        if (Arrays.equals(dealerPass, oldPass.getPassword())) {
            try {
                // Create file
                FileWriter fstream = new FileWriter("Password.txt");
                BufferedWriter out = new BufferedWriter(fstream);

                char[] pass = newPass.getPassword();
                encrypt(pass);
                out.write(pass);

                out.close();
            } catch (Exception e) {//Catch exception if any
                userMessage.showMessageDialog(this, "Error in Changing Password: " + e);
            }

        // If password does not match, show message
        } else {
            userMessage.showMessageDialog(this, "Incorrect Password !!");
        }

        changePass.dispose();
    }//GEN-LAST:event_okPassActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        changePass.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Runtime.getRuntime().gc();
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton changePasButton;
    private javax.swing.JDialog changePass;
    private javax.swing.JButton d_logIn;
    private javax.swing.JButton exit;
    private javax.swing.JButton ext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JButton okPass;
    private javax.swing.JPasswordField oldPass;
    private javax.swing.JButton p_logIn;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JOptionPane userMessage;
    // End of variables declaration//GEN-END:variables

    // Global Variables used throughout the program.
    public char[] dealerPass;
    public char[] password;

    // Method to encrypt password
    public void encrypt(char[] a) {
        for (int i = 0; i < a.length; ++i) {
            a[i] += 4;
        }
    }

    // Method to decrypt password
    public void decrypt(char[] a) {
        for (int i = 0; i < a.length; ++i) {
            a[i] -= 4;
        }
    }
}


